image: docker:git

services:
  - docker:dind

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: "1"

build:
  stage: build
  script:
    - sh docker.sh
  artifacts:
    paths:
      - "artifacts/*"
