image: docker/compose:latest

services:
  - docker:dind

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: "1"

build:
  stage: build
  script:
    - mkdir Artifacts
    - GIT_HASH=${GIT_SHA1} docker-compose up
    - docker-compose down --volumes
    - cp -R Artifacts/* .
  artifacts:
    paths:
      - GlueSample_Linux_x86_64_$CI_COMMIT_SHORT_SHA.zip
      - GlueSample_Windows_x86_64_$CI_COMMIT_SHORT_SHA.zip
      - GlueSample_Darwin_x86_64_$CI_COMMIT_SHORT_SHA.zip
      - GlueSample_Android_x86_64_$CI_COMMIT_SHORT_SHA.apk
