image: docker:git

services:
  - docker:dind

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: "1"

build:
  stage: build
  script:
    - docker-compose -f docker-compose-3rd.yml up
    - docker-compose -f docker-compose-3rd.yml down --volumes
  artifacts:
    paths:
      - Artifacts/GlueSample_Linux_x86_64_$CI_COMMIT_SHORT_SHA.zip
      - Artifacts/GlueSample_Windows_x86_64_$CI_COMMIT_SHORT_SHA.zip
      - Artifacts/GlueSample_Darwin_x86_64_$CI_COMMIT_SHORT_SHA.zip
      - Artifacts/GlueSample_Android_x86_64_$CI_COMMIT_SHORT_SHA.apk
