image: tmaier/docker-compose:latest

services:
  - docker:dind

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: "1"

build:
  stage: build
  script:
    - GIT_HASH=${GIT_SHA1} docker-compose up
    - docker-compose down --volumes
  artifacts:
    paths:
      - Artifacts/GlueSample_Linux_x86_64_$CI_COMMIT_SHORT_SHA.zip
      - Artifacts/GlueSample_Windows_x86_64_$CI_COMMIT_SHORT_SHA.zip
      - Artifacts/GlueSample_Darwin_x86_64_$CI_COMMIT_SHORT_SHA.zip
      - Artifacts/GlueSample_Android_x86_64_$CI_COMMIT_SHORT_SHA.apk
