image: docker:git

services:
  - docker:dind

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: "1"

build:
  stage: build
  script:
    - mkdir artifacts
    - git clone --depth 1 https://github.com/balrogcpp/scenes.git assets && rm -rf assets/.git
    - docker build --build-arg GIT_HASH=`git rev-parse --short=8 HEAD` . -f docker/sample/linux.Dockerfile -t glue/sample-linux
    - docker create -ti --name abc glue/sample-linux bash
    - docker cp abc:/mnt/build/artifacts/GlueSample-linux-clang-x86_64-$CI_COMMIT_SHORT_SHA.zip artifacts
    - docker rm -f abc
    - docker rmi glue/sample-linux
    - docker build --build-arg GIT_HASH=`git rev-parse --short=8 HEAD` . -f docker/sample/windows.Dockerfile -t glue/sample-windows
    - docker create -ti --name abc glue/sample-windows bash
    - docker cp abc:/mnt/build/artifacts/GlueSample-windows-clang-mingw-x86_64-$CI_COMMIT_SHORT_SHA.zip artifacts
    - docker rm -f abc
    - docker rmi glue/sample-windows
    - docker build --build-arg GIT_HASH=`git rev-parse --short=8 HEAD` . -f docker/sample/apple.Dockerfile -t glue/sample-apple
    - docker create -ti --name abc balrogcpp/sample-apple bash
    - docker cp abc:/mnt/build/artifacts/GlueSample-apple-darwin-clang-x86_64-$CI_COMMIT_SHORT_SHA.zip artifacts
    - docker rm -f abc
    - docker rmi glue/sample-apple
  artifacts:
    paths:
      - artifacts/GlueSample-linux-clang-x86_64-$CI_COMMIT_SHORT_SHA.zip
      - artifacts/GlueSample-windows-clang-mingw-x86_64-$CI_COMMIT_SHORT_SHA.zip
