image: docker:git

services:
  - docker:dind

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: "1"

build:
  stage: build
  script:
    - docker build --build-arg GIT_HASH=`git rev-parse --short=8 HEAD`  . -f docker/xio-linux/Dockerfile -t balrogcpp/xio-linux
    - docker create -ti --name abc balrogcpp/xio-linux bash
    - mkdir artifacts
    - docker cp abc:/mnt/build/artifacts/ContextProjectDemo-linux-clang-x86_64-$CI_COMMIT_SHORT_SHA.zip artifacts
    - docker rm -f abc
    - docker rmi balrogcpp/xio-linux
    - docker rmi balrogcpp/deps-linux
    - docker build --build-arg GIT_HASH=`git rev-parse --short=8 HEAD`  . -f docker/xio-cross/Dockerfile -t balrogcpp/xio-cross
    - docker create -ti --name abc balrogcpp/xio-cross bash
    - docker cp abc:/mnt/build/artifacts/ContextProjectDemo-windows-clang-mingw-x86_64-$CI_COMMIT_SHORT_SHA.zip artifacts
    - docker cp abc:/mnt/build/artifacts/ContextProjectDemo-apple-darwin-clang-x86_64-$CI_COMMIT_SHORT_SHA.zip artifacts
    - docker cp abc:/mnt/build/artifacts/app-arm64-v8a-$CI_COMMIT_SHORT_SHA.apk artifacts
    - docker rm -f abc
    - docker rmi balrogcpp/xio-cross
    - docker rmi balrogcpp/deps-cross
  artifacts:
    paths:
      - artifacts/ContextProjectDemo-linux-clang-x86_64-$CI_COMMIT_SHORT_SHA.zip
      - artifacts/ContextProjectDemo-windows-clang-mingw-x86_64-$CI_COMMIT_SHORT_SHA.zip
      - artifacts/ContextProjectDemo-apple-darwin-clang-x86_64-$CI_COMMIT_SHORT_SHA.zip
      - artifacts/app-arm64-v8a-$CI_COMMIT_SHORT_SHA.apk
