image: docker/compose:latest

services:
  - docker:dind

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: "1"

build:
  stage: build
  script:
    - mkdir Artifacts
    - GIT_HASH=$CI_COMMIT_SHORT_SHA docker-compose up
    - docker-compose down --volumes
  artifacts:
    paths:
      - "Artifacts/*"
