image: docker:edge-git

services:
  - docker:dind

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: "1"

# If you only need compose in a specific step definitely put this
# only in that step so it's not executed unnecessarily
before_script:
  - apk add --no-cache py2-pip && pip install docker-compose

build:
  stage: build
  script:
    - docker-compose -f docker-compose-3rd.yml up
    - docker-compose -f docker-compose-3rd.yml down --volumes
  artifacts:
    paths:
      - Artifacts/GlueSample_Linux_x86_64_$CI_COMMIT_SHORT_SHA.zip
      - Artifacts/GlueSample_Windows_x86_64_$CI_COMMIT_SHORT_SHA.zip
      - Artifacts/GlueSample_Darwin_x86_64_$CI_COMMIT_SHORT_SHA.zip
      - Artifacts/GlueSample_Android_x86_64_$CI_COMMIT_SHORT_SHA.apk
