image: docker:git

services:
  - docker:dind

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  script:
    - docker build . -t context
    - docker create -ti --name abc context bash
    - mkdir artifacts
    - docker cp abc:/mnt/build/install/ContextProjectDemo-Release-$CI_COMMIT_SHORT_SHA.zip .
    - docker rm -f abc
  artifacts:
    paths:
      - ContextProjectDemo-Release-$CI_COMMIT_SHORT_SHA.zip
  only:
    - master
