image: docker:git

services:
  - docker:dind

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: "1"

build:
  stage: build
  script:
    - "./build.sh"
  artifacts:
    paths:
      - artifacts/ContextProjectDemo-Windows-x64-$CI_COMMIT_SHORT_SHA.zip
      - artifacts/ContextProjectDemo-Linux-x64-$CI_COMMIT_SHORT_SHA.zip
  only:
    - master
