image: docker:git

services:
  - docker:dind

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: "1"

build:
  stage: build
  script:
    - docker build --build-arg GIT_HASH=`git rev-parse --short=8 HEAD` . -f Docker/Tests/linux.Dockerfile -t glue/sample-linux
    - docker create -ti --name abc glue/sample-linux bash
    - docker cp abc:/mnt/build/Artifacts/GlueSample_Linux_x86_64_$CI_COMMIT_SHORT_SHA.zip Artifacts
    - docker rm -f abc
    - docker rmi glue/sample-linux
    - docker build --build-arg GIT_HASH=`git rev-parse --short=8 HEAD` . -f Docker/Tests/windows.Dockerfile -t glue/sample-windows
    - docker create -ti --name abc glue/sample-windows bash
    - docker cp abc:/mnt/build/Artifacts/GlueSample_Windows_x86_64_$CI_COMMIT_SHORT_SHA.zip Artifacts
    - docker rm -f abc
    - docker rmi glue/sample-windows
    - docker build --build-arg GIT_HASH=`git rev-parse --short=8 HEAD` . -f Docker/Tests/apple.Dockerfile -t glue/sample-apple
    - docker create -ti --name abc glue/sample-apple bash
    - docker cp abc:/mnt/build/Artifacts/GlueSample_Darwin_x86_64_$CI_COMMIT_SHORT_SHA.zip Artifacts
    - docker rm -f abc
    - docker rmi glue/sample-apple
  artifacts:
    paths:
      - Artifacts/GlueSample_Linux_x86_64_$CI_COMMIT_SHORT_SHA.zip
      - Artifacts/GlueSample_Windows_x86_64_$CI_COMMIT_SHORT_SHA.zip
      - Artifacts/GlueSample_Darwin_x86_64_$CI_COMMIT_SHORT_SHA.zip
