version: "3.3"
services:
  app-linux:
    build:
      context: .
      dockerfile: ./docker/build-linux/Dockerfile
      args:
        GIT_HASH: ${GIT_HASH}
    container_name: build-linux
    volumes:
      - .:/var/artifacts
    command: cp -R /mnt/build/artifacts /var/artifacts
  app-cross:
    build:
      context: .
      dockerfile: ./docker/build-cross/Dockerfile
      args:
        GIT_HASH: ${GIT_HASH}
    container_name: build-cross
    volumes:
      - .:/var/artifacts
    command: cp -R /mnt/build/artifacts /var/artifacts
