version: "3.3"
services:
  dependencies-linux:
    build:
      context: .
      dockerfile: Docker/Dependencies/linux-dependencies.Dockerfile
      args:
        GIT_HASH: ${GIT_HASH}
    container_name: linux-dependencies
    volumes:
      - .:/var/artifacts
    command: cp -R /mnt/build/Artifacts /var/artifacts
  dependencies-windows:
    build:
      context: .
      dockerfile: Docker/Dependencies/windows-dependencies.Dockerfile
      args:
        GIT_HASH: ${GIT_HASH}
    container_name: windows-dependencies
    volumes:
      - .:/var/artifacts
    command: cp -R /mnt/build/Artifacts /var/artifacts
  dependencies-apple:
    build:
      context: .
      dockerfile: Docker/Dependencies/darwin-dependencies.Dockerfile
      args:
        GIT_HASH: ${GIT_HASH}
    container_name: apple-dependencies
    volumes:
      - .:/var/artifacts
    command: cp -R /mnt/build/Artifacts /var/artifacts
  dependencies-android:
    build:
      context: .
      dockerfile: Docker/Dependencies/android-dependencies.Dockerfile
      args:
        GIT_HASH: ${GIT_HASH}
    container_name: android-dependencies
    volumes:
      - .:/var/artifacts
    command: cp -R /mnt/build/Artifacts /var/artifacts
