version: "3.3"
services:
  dependencies-linux:
    build:
      context: .
      dockerfile: Docker/ThirdParty/linux-3rd.Dockerfile
      args:
        GIT_HASH: ${GIT_HASH}
    container_name: linux-dependencies
    volumes:
      - .:/var/artifacts
    command: cp -R /mnt/build/Artifacts /var/artifacts
  dependencies-windows:
    build:
      context: .
      dockerfile: Docker/ThirdParty/windows-3rd.Dockerfile
      args:
        GIT_HASH: ${GIT_HASH}
    container_name: windows-dependencies
    volumes:
      - .:/var/artifacts
    command: cp -R /mnt/build/Artifacts /var/artifacts
  dependencies-apple:
    build:
      context: .
      dockerfile: Docker/ThirdParty/darwin-3rd.Dockerfile
      args:
        GIT_HASH: ${GIT_HASH}
    container_name: apple-dependencies
    volumes:
      - .:/var/artifacts
    command: cp -R /mnt/build/Artifacts /var/artifacts
  dependencies-android:
    build:
      context: .
      dockerfile: Docker/ThirdParty/android-3rd.Dockerfile
      args:
        GIT_HASH: ${GIT_HASH}
    container_name: android-dependencies
    volumes:
      - .:/var/artifacts
    command: cp -R /mnt/build/Artifacts /var/artifacts
