version: "3.3"
services:
  sample-linux:
    build:
      context: .
      dockerfile: ./sample/linux.Dockerfile
      args:
        GIT_HASH: ${GIT_HASH}
    container_name: sample-linux
    volumes:
      - .:/var/artifacts
    command: mv -R /mnt/build/artifacts /var/artifacts
  sample-windows:
    build:
      context: .
      dockerfile: ./sample/windows.Dockerfile
      args:
        GIT_HASH: ${GIT_HASH}
    container_name: sample-windows
    volumes:
      - .:/var/artifacts
    command: mv -R /mnt/build/artifacts /var/artifacts
  sample-apple:
    build:
      context: .
      dockerfile: ./sample/apple.Dockerfile
      args:
        GIT_HASH: ${GIT_HASH}
    container_name: sample-apple
    volumes:
      - .:/var/artifacts
    command: mv -R /mnt/build/artifacts /var/artifacts
  sample-android:
    build:
      context: .
      dockerfile: ./sample/android.Dockerfile
      args:
        GIT_HASH: ${GIT_HASH}
    container_name: sample-android
    volumes:
      - .:/var/artifacts
    command: mv -R /mnt/build/artifacts /var/artifacts
