version: "3.3"
services:
  glue-dep-unicross:
    build:
      context: .
      dockerfile: Docker/ThirdParty/unicross.Dockerfile
      args:
        GIT_HASH: ${GIT_HASH}
    container_name: unicross-3rd
    volumes:
      - .:/var/artifacts
    command: cp -R /mnt/build/Artifacts /var/artifacts
  glue-dep-android:
    build:
      context: .
      dockerfile: Docker/ThirdParty/android.Dockerfile
      args:
        GIT_HASH: ${GIT_HASH}
    container_name: android-3rd
    volumes:
      - .:/var/artifacts
    command: cp -R /mnt/build/Artifacts /var/artifacts
