# include guard
if (_buildvariables_included)
    return()
endif (_buildvariables_included)
set(_buildvariables_included true)

list(APPEND CMAKE_PREFIX_PATH ${DEPS_ROOT})
list(APPEND CMAKE_FIND_ROOT_PATH ${DEPS_ROOT})

macro(add_external_package package)
    if (NO_DEPS)
        find_package(${package})
    else ()
        find_package(${package} REQUIRED)
    endif ()
endmacro()

macro(add_external_package_static package)
    set(_OLD_FIND_SUFFIXES ${CMAKE_FIND_LIBRARY_SUFFIXES})
    set(CMAKE_FIND_LIBRARY_SUFFIXES ".lib" ".a" ".sl" ".dylib" ".dll.a")
    if (NO_DEPS)
        find_package(${package})
    else ()
        find_package(${package} REQUIRED)
    endif ()
    set(CMAKE_FIND_LIBRARY_SUFFIXES ${_OLD_FIND_SUFFIXES})
    unset(_OLD_FIND_SUFFIXES)
endmacro()

# check dependencies
set(CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH FALSE)
set(CMAKE_FIND_USE_PACKAGE_REGISTRY FALSE)
set(CMAKE_FIND_USE_CMAKE_SYSTEM_PATH FALSE)
set(CMAKE_FIND_USE_INSTALL_PREFIX FALSE)

add_external_package(OpenAL)
add_external_package_static(SDL2)
add_external_package_static(Bullet)
add_external_package_static(Ogg)
add_external_package_static(Vorbis)
add_external_package_static(OpenSSL)
add_external_package_static(Lua)
add_external_package_static(sol2)
add_external_package_static(sodium)
add_external_package_static(yojimbo)

set(CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH TRUE)
set(CMAKE_FIND_USE_PACKAGE_REGISTRY TRUE)
set(CMAKE_FIND_USE_CMAKE_SYSTEM_PATH TRUE)
set(CMAKE_FIND_USE_INSTALL_PREFIX TRUE)

set(OGRE_STATIC 1)
set(OGRE_IGNORE_ENV 1)
add_external_package(OGRE)


# engine
set(ENGINE_SOURCE_DIR ${CMAKE_SOURCE_DIR}/Source/Engine)
set(ENGINE_LINK_DIRS ${DEPS_ROOT}/lib ${DEPS_ROOT}/lib/OGRE)
set(ENGINE_INCLUDE_DIRS ${ENGINE_SOURCE_DIR} ${ENGINE_SOURCE_DIR}/Code ${CMAKE_BINARY_DIR}/Source ${DEPS_ROOT}/include)

if (OGRE_FOUND)
    list(APPEND ENGINE_LIBRARIES ${OGRE_LIBRARIES})
    list(APPEND ENGINE_INCLUDE_DIRS ${OGRE_INCLUDE_DIRS})
endif ()
if (Bullet_FOUND)
    list(APPEND ENGINE_LIBRARIES ${BULLET_LIBRARIES})
    list(APPEND ENGINE_INCLUDE_DIRS ${BULLET_INCLUDE_DIRS})
endif ()
if (Lua_FOUND)
    list(APPEND ENGINE_LIBRARIES ${LUA_LIBRARY})
    list(APPEND ENGINE_INCLUDE_DIRS ${LUA_INCLUDE_DIR})
endif ()
if (Vorbis_FOUND)
    list(APPEND ENGINE_LIBRARIES ${VORBIS_LIBRARIES})
    list(APPEND ENGINE_INCLUDE_DIRS ${VORBIS_INCLUDE_DIRS})
endif ()
if (Ogg_FOUND)
    list(APPEND ENGINE_LIBRARIES ${OGG_LIBRARIES})
    list(APPEND ENGINE_INCLUDE_DIRS ${OGG_INCLUDE_DIRS})
endif ()
if (OpenAL_FOUND)
    list(APPEND ENGINE_LIBRARIES ${OPENAL_LIBRARY})
    list(APPEND ENGINE_INCLUDE_DIRS ${OPENAL_INCLUDE_DIR})
endif ()
if (TARGET SDL2::SDL2-static)
    list(APPEND ENGINE_LIBRARIES SDL2::SDL2-static)
endif ()
if (yojimbo_FOUND)
    list(APPEND ENGINE_LIBRARIES yojimbo::yojimbo)
endif ()
if (OpenSSL_FOUND)
    list(APPEND ENGINE_LIBRARIES ${OPENSSL_CRYPTO_LIBRARIES} ${OPENSSL_SSL_LIBRARIES})
    list(APPEND ENGINE_INCLUDE_DIRS ${OPENSSL_INCLUDE_DIR})
endif ()
