# This file is part of Glue Engine. Created by Andrey Vasiliev

# GLUE_SOURCE_DIR, GLUE_ENGINE_SOURCE_FILES, GLUE_INCLUDE_DIRS, GLUE_LINK_DIRS, GLUE_LIBRARIES


include(Platform)


set(GLUE_SOURCE_DIR ${CMAKE_SOURCE_DIR}/source/Engine)

set(GLUE_INCLUDE_DIRS
        ${GLUE_SOURCE_DIR}
        ${GLUE_SOURCE_DIR}/Code
        ${GLUE_THIRDPARTY_ROOT}/include
        )


set(GLUE_LINK_DIRS ${GLUE_THIRDPARTY_ROOT}/lib ${GLUE_THIRDPARTY_ROOT}/lib/OGRE)


if (MINGW)
    list(APPEND SYSTEM_LIBRARIES imagehlp dinput8 dxguid dxerr8 user32 gdi32 imm32 winmm ole32 oleaut32 shell32 version uuid setupapi hid)
elseif (LINUX)
    list(APPEND SYSTEM_LIBRARIES X11 Xrandr dl)
elseif (APPLE)
    list(APPEND SYSTEM_LIBRARIES z)
elseif (ANDROID)
    list(APPEND SYSTEM_LIBRARIES android atomic EGL GLESv1_CM GLESv2 log OpenSLES)
elseif (MSVC)
    list(APPEND SYSTEM_LIBRARIES winmm Version imm32 Setupapi)
endif ()


if (OGRE_FOUND)
    list(APPEND GLUE_LIBRARIES ${OGRE_LIBRARIES})
    list(APPEND GLUE_INCLUDE_DIRS ${OGRE_INCLUDE_DIRS})
endif ()
if (TARGET SDL2::SDL2-static)
    list(APPEND GLUE_LIBRARIES SDL2::SDL2-static)
    list(APPEND GLUE_INCLUDE_DIRS ${SDL2_INCLUDE_DIRS})
endif ()
if (TARGET pugixml::static)
    list(APPEND GLUE_LIBRARIES pugixml::static)
    list(APPEND GLUE_INCLUDE_DIRS ${PUGIXML_INCLUDE_DIRS})
endif ()
if (Bullet_FOUND)
    list(APPEND GLUE_LIBRARIES ${BULLET_LIBRARIES})
    list(APPEND GLUE_INCLUDE_DIRS ${BULLET_INCLUDE_DIRS})
endif ()
if (Vorbis_FOUND)
    list(APPEND GLUE_LIBRARIES ${VORBIS_LIBRARIES})
    list(APPEND GLUE_INCLUDE_DIRS ${VORBIS_INCLUDE_DIRS})
endif ()
if (Ogg_FOUND)
    list(APPEND GLUE_LIBRARIES ${OGG_LIBRARIES})
    list(APPEND GLUE_INCLUDE_DIRS ${OGG_INCLUDE_DIRS})
endif ()
if (OpenAL_FOUND)
    list(APPEND GLUE_LIBRARIES ${OPENAL_LIBRARY})
    list(APPEND GLUE_INCLUDE_DIRS ${OPENAL_INCLUDE_DIR})
endif ()
if (Lua_FOUND)
    list(APPEND GLUE_LIBRARIES ${LUA_LIBRARY})
    list(APPEND GLUE_INCLUDE_DIRS ${LUA_INCLUDE_DIR})
endif ()
list(APPEND GLUE_LIBRARIES ${SYSTEM_LIBRARIES})
