# include guard
if (_buildvariables_included)
    return()
endif (_buildvariables_included)
set(_buildvariables_included true)

list(APPEND CMAKE_PREFIX_PATH ${DEPS_ROOT})
list(APPEND CMAKE_FIND_ROOT_PATH ${DEPS_ROOT})

macro(add_external_package package)
    if (DISABLE_DEPENDENCIES_BUILD)
        find_package(${package})
    else ()
        find_package(${package} REQUIRED)
    endif ()
endmacro()

macro(add_external_package_static package)
    set(_OLD_FIND_SUFFIXES ${CMAKE_FIND_LIBRARY_SUFFIXES})
    set(CMAKE_FIND_LIBRARY_SUFFIXES ".lib" ".a" ".sl" ".dylib" ".dll.a")
    if (DISABLE_DEPENDENCIES_BUILD)
        find_package(${package})
    else ()
        find_package(${package} REQUIRED)
    endif ()
    set(CMAKE_FIND_LIBRARY_SUFFIXES ${_OLD_FIND_SUFFIXES})
    unset(_OLD_FIND_SUFFIXES)
endmacro()

# check dependencies
set(CMAKE_FIND_USE_CMAKE_SYSTEM_PATH FALSE)

add_external_package(OpenAL)
add_external_package_static(SDL2)
add_external_package_static(Bullet)
add_external_package_static(Ogg)
add_external_package_static(Vorbis)
#add_external_package_static(LibreSSL)
#add_external_package_static(Lua)
#add_external_package_static(sol2)
#add_external_package_static(sodium)
#add_external_package_static(yojimbo)
set(OGRE_STATIC 1)
set(OGRE_IGNORE_ENV 1)
add_external_package(OGRE)

set(CMAKE_FIND_USE_CMAKE_SYSTEM_PATH TRUE)
if (OGRE_GL3_LIBRARY OR OGRE_GL_LIBRARY)
    find_package(OpenGL REQUIRED)
    if (OPENGL_FOUND)
        list(APPEND OGRE_INCLUDE_DIRS ${OPENGL_INCLUDE_DIR})
        list(APPEND OGRE_LIBRARIES ${OPENGL_LIBRARIES})
    endif ()
endif ()
if (OGRE_GLES2_LIBRARY)
    find_package(OpenGL COMPONENTS EGL)
    if (OpenGL_EGL_FOUND)
        list(APPEND OGRE_INCLUDE_DIRS ${OPENGL_EGL_INCLUDE_DIRS})
        list(APPEND OGRE_LIBRARIES ${OPENGL_egl_LIBRARY})
    endif ()
endif ()
if (OGRE_VULKAN_LIBRARY)
    find_package(Vulkan REQUIRED)
    if (Vulkan_FOUND)
        list(APPEND OGRE_INCLUDE_DIRS ${Vulkan_INCLUDE_DIRS})
        list(APPEND OGRE_LIBRARIES ${Vulkan_LIBRARIES})
    endif ()
endif ()

# engine
set(ENGINE_SOURCE_DIR ${CMAKE_SOURCE_DIR}/Source/Engine)
set(ENGINE_LINK_DIRS ${DEPS_ROOT}/lib ${DEPS_ROOT}/lib/OGRE)
set(ENGINE_INCLUDE_DIRS ${ENGINE_SOURCE_DIR} ${ENGINE_SOURCE_DIR}/Code ${CMAKE_BINARY_DIR}/Source ${DEPS_ROOT}/include)

if (OGRE_FOUND)
    list(APPEND ENGINE_LIBRARIES ${OGRE_LIBRARIES})
    list(APPEND ENGINE_INCLUDE_DIRS ${OGRE_INCLUDE_DIRS})
endif ()
if (Bullet_FOUND)
    list(APPEND ENGINE_LIBRARIES ${BULLET_LIBRARIES})
    list(APPEND ENGINE_INCLUDE_DIRS ${BULLET_INCLUDE_DIRS})
endif ()
if (Lua_FOUND)
    list(APPEND ENGINE_LIBRARIES ${LUA_LIBRARY})
    list(APPEND ENGINE_INCLUDE_DIRS ${LUA_INCLUDE_DIR})
endif ()
if (Vorbis_FOUND)
    list(APPEND ENGINE_LIBRARIES ${VORBIS_LIBRARIES})
    list(APPEND ENGINE_INCLUDE_DIRS ${VORBIS_INCLUDE_DIRS})
endif ()
if (Ogg_FOUND)
    list(APPEND ENGINE_LIBRARIES ${OGG_LIBRARIES})
    list(APPEND ENGINE_INCLUDE_DIRS ${OGG_INCLUDE_DIRS})
endif ()
if (OpenAL_FOUND)
    list(APPEND ENGINE_LIBRARIES ${OPENAL_LIBRARY})
    list(APPEND ENGINE_INCLUDE_DIRS ${OPENAL_INCLUDE_DIR})
endif ()
if (TARGET SDL2::SDL2-static)
    list(APPEND ENGINE_LIBRARIES SDL2::SDL2-static)
endif ()
if (yojimbo_FOUND)
    list(APPEND ENGINE_LIBRARIES yojimbo::yojimbo)
endif ()
if (LibreSSL_FOUND)
    list(APPEND ENGINE_LIBRARIES ${LIBRESSL_LIBRARIES})
    list(APPEND ENGINE_INCLUDE_DIRS ${LIBRESSL_INCLUDE_DIR})
endif ()
