macro(subdirlist result curdir)
   file(GLOB children RELATIVE ${curdir}/*)
   set(dirlist "")
   foreach (child ${children})
       if (IS_DIRECTORY ${curdir}/${child})
           list(APPEND dirlist ${child})
       endif ()
   endforeach ()
   set(${result} ${dirlist})
endmacro()

macro(zipdirlist curdir destination)
   execute_process(COMMAND ${CMAKE_COMMAND} -E make_directory ${CONTEXT_TEMP_DIR}/${destination})
   file(GLOB children RELATIVE ${curdir} ${curdir}/*)
   set(dirlist "")
   foreach (child ${children})
       set(filelist "")
       if (IS_DIRECTORY ${curdir}/${child})
           file(GLOB children2 RELATIVE ${curdir}/${child} ${curdir}/${child}/*)
           foreach (child2 ${children2})
               if (NOT IS_DIRECTORY ${curdir}/${child}/${child2})
                   list(APPEND filelist ${child2})
               endif ()
           endforeach ()
           list(APPEND dirlist ${child})
           execute_process(COMMAND ${CMAKE_COMMAND} -E chdir "${curdir}/${child}/" ${CMAKE_COMMAND} -E tar "cf" "${CONTEXT_TEMP_DIR}/${destination}/${child}.zip" --format=zip ${filelist})
       endif ()
   endforeach ()
endmacro()

macro(copydirlist curdir destination)
   execute_process(COMMAND ${CMAKE_COMMAND} -E make_directory ${CONTEXT_TEMP_DIR}/${destination})
   execute_process(COMMAND ${CMAKE_COMMAND} -E copy_directory ${curdir} ${CONTEXT_TEMP_DIR}/${destination})
endmacro()

set(CONTEXT_PROGRAMS_DIR ${CMAKE_SOURCE_DIR}/programs)
set(CONTEXT_SCENES_DIR ${CMAKE_SOURCE_DIR}/scenes)
set(CONTEXT_TMP_DIR ${CMAKE_SOURCE_DIR}/tmp)
zipdirlist(${CONTEXT_PROGRAMS_DIR} ${CONTEXT_TMP_DIR}/programs)
zipdirlist(${CONTEXT_SCENES_DIR} ${CONTEXT_TMP_DIR}/scenes)