name: CI Build
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: addnab/docker-run-action@v3
        with:
          registry: docker.io
          image: docker:latest
          options: -v ${{ github.workspace }}:/mnt
          run: |
            apt-get update
            apt-get install -y --
            sh docker.sh
          name: artifacts
          path: "Artifacts/*"
